#[46]식당 리스트 조회 기능 수정
f-lab-edu/eat-enjoy pull request #50
Opened 2021-04-29 13:25 UTC by sjhello

2021-04-29 15:10 UTC, sigriswil commented on src/main/java/com/restaurant/eatenjoy/service/RestaurantService.java
> +		if (Objects.isNull(lastRestaurantId)) {
데이터 조회 후 lastRestaurantId 값을 체크하는 이유가 있나요?

2021-04-29 15:12 UTC, sjhello commented on src/main/java/com/restaurant/eatenjoy/service/RestaurantService.java
> +		if (Objects.isNull(lastRestaurantId)) {
아 그러네요
체크 후 조회하는 것으로 수정 하겠습니다~

2021-04-29 15:18 UTC, sigriswil commented on src/main/resources/mapper/RestaurantMapper.xml
> +         LIMIT 3
1. 해당 조건문은
```sql
WHERE owner_id = #{ownerId}
        <if test=" lastRestaurantId != 0 ">
              AND id <![CDATA[ < ]]> #{lastRestaurantId}
        </if>
```
이게 더 가독성에 좋을꺼 같네요.
2. 식당을 내림차순으로 정렬할 필요가 있을까요?
3. 3개씩 조회하는건 너무 적지 않나요?

2021-04-29 15:23 UTC, sigriswil commented on src/main/java/com/restaurant/eatenjoy/service/RestaurantService.java
>  		if (Objects.isNull(lastRestaurantId)) {
음 그리고 lastRestaurantId 파라미터 값이 null 로 요청이 왔다는건 서비스에서 예외 체크하는 것보단 
컨트롤러에서 체크하는게 더 좋지 않을까요??

2021-04-29 15:30 UTC, sjhello commented on src/main/java/com/restaurant/eatenjoy/service/RestaurantService.java
>  		if (Objects.isNull(lastRestaurantId)) {
컨트롤러의 책임은 요청을 받아서 서비스로 위임하는 역할이라고 생각했기 떄문에 컨트롤러에서 NULL 체크하는 것보다는 서비스에서 체크하는게 좋지 않을까요?

2021-04-29 15:32 UTC, sjhello commented on src/main/resources/mapper/RestaurantMapper.xml
> +         LIMIT 3
- 내림차순 정렬 이유는 최근에 등록한 식당 먼저 보여주기 위해서 적용 하였습니다
- 어느정도의 식당 갯수를 가지고 있을지 예측이 안가서 적당히 10으로 할까요?

2021-04-29 15:45 UTC, sigriswil commented on src/main/java/com/restaurant/eatenjoy/service/RestaurantService.java
>  		if (Objects.isNull(lastRestaurantId)) {
컨트롤러에서 요청받은 파라미터 값 기본인 유효성 검사는 컨트롤러에서 이루어져야 한다고 생각하고, 
서비스는 해당 값의 비지니스적인 유효성을 검사하는게 맞다고 생각합니다.
상진님 말씀대로라면 POST 요청시 요청받은 Dto 객체에 @Valid 애노테이션 사용해서 입력 값 검증을 
컨트롤러에서 하는 이유가 있을까요??

2021-04-29 15:47 UTC, sigriswil commented on src/main/resources/mapper/RestaurantMapper.xml
> +         LIMIT 3
식당 같은 경우에는 게시글 같은 개념이 아니라 굳이 내림차순 할 필요는 없다고 저는 생각합니다..
디폴트로 10 하는게 좋을꺼 같습니다.

2021-04-29 16:38 UTC, sjhello commented on src/main/resources/mapper/RestaurantMapper.xml
> +         LIMIT 3
뭐 굳이 내림차순 정렬을 할 필요는 없겠지만 제 나름대로 내림차순 정렬 적용 시 장점을 생각해보자면
내림차순 정렬인지 아닌지 결정하는것은 정책적인 부분인거 같지만
 - 내림차순 정렬 적용의 장점으로는 사용자 편의성 부분에 있어서 장점이 될거 같습니다.

예를 들어 10개 이상의 식당을 가진 사장님이 식당을 추가로 등록한다고 하였을때 추가한 식당의 정보를 수정하거나 보기 위해서는 오름차순으로 정렬 시 스크롤을 아래로 다시 내려야 하는 액션을 추가적으로 해야 할 것 같습니다.

사장님 한명이 가지는 식당 갯수가 얼마나 될지는 모르겠으나 많은 식당을 보유한 사장님일 수록 스크롤을 아래로 내려야 될 것 같네요
사용자 편의성을 생각해보았을때 추가 후 식당 리스트 화면에 맨 위에 최근 등록한 식당이 뜨는게 사용자한테는 더 좋은거 같습니다

주완님 생각에는 내림차순을 적용했을때 어떠한 단점이 있을것 같다는 생각에 리뷰를 해주신걸까요?

2021-04-30 00:24 UTC, sigriswil commented on src/main/resources/mapper/RestaurantMapper.xml
> +         LIMIT 3
단점이라기 보단 앞서 말씀드린거와 같이 식당 같은 경우 자주 등록하는 것도 아니고 게시글 같은 개념도 아니라서 
굳이 최신 등록된 식당일 우선적으로 오너가 먼저 볼 필요가 없다고 생각합니다.
굳이 정렬이 필요하다면 사용자가 화면에서 정렬 관련 버튼을 이용해서 유동적으로 순서를 바꿀 수 있겠네요,

2021-04-30 15:26 UTC, f-lab-dev commented on src/main/resources/mapper/RestaurantMapper.xml
> -            ORDER BY id DESC
정렬을 지우신 이유가 있으신가요??

2021-05-01 13:51 UTC, sjhello commented on src/main/resources/mapper/RestaurantMapper.xml
> -            ORDER BY id DESC
주완님 생각대로 굳이 최근 등록된 식당을 먼저 보여줄 필요는 없는 것 같아서 정렬을 지웠습니다~

2021-05-01 14:56 UTC, f-lab-dev commented on src/main/resources/mapper/RestaurantMapper.xml
> -            ORDER BY id DESC
커서방식 페이징이 들어가는데 그럼 `ORDER BY`를 붙여주지 않더라도 정렬이 보장될까요?

2021-05-01 15:36 UTC, sjhello commented on src/main/resources/mapper/RestaurantMapper.xml
> -            ORDER BY id DESC
커서방식 페이징은 정렬기준(고유값)이 필요하기 때문에 ORDER BY 적용이 필요해 보이네요...
수정 하겠습니다

2021-05-02 12:11 UTC, f-lab-dev approved these changes

2021-05-02 12:11 UTC, f-lab-dev requested changes
아 최신순으로 보여줄거면 DESC 아닐까요?

2021-05-02 13:18 UTC, sjhello commented
> 아 최신순으로 보여줄거면 DESC 아닐까요?

2021-05-02 13:19 UTC, sjhello commented
> 아 최신순으로 보여줄거면 DESC 아닐까요?

최신순으로 보여줄 필요는 없는거같아서 DESC를 뺐습니다

2021-05-03 08:12 UTC, f-lab-dev approved these changes

2021-05-03 13:44 UTC, merged