[#53] profile별 이메일 기능 분리
f-lab-edu/eat-enjoy pull request #55
Opened 2021-05-03 14:36 UTC by sigriswil

2021-05-04 15:32 UTC, f-lab-dev commented on src/main/java/com/restaurant/eatenjoy/util/mail/ConsoleMailService.java
> +		String checkMailTokenUrl = "http://localhost:8080/api/ROLE/check-mail-token?email=EMAIL&token=TOKEN"
여기있는 문자열은 하드코딩이 되어있어서 여러곳에서 재사용이 힘들어보입니다. `@Profile`이 붙어있다고 하지만 하드코딩은 지양하는게 좋습니다~

2021-05-04 15:32 UTC, f-lab-dev commented on src/main/java/com/restaurant/eatenjoy/util/mail/HtmlMailService.java
> +			throw new NotFoundException("메일 양식을 찾을 수 없습니다.");
만약 클래스를 로딩할때 static 구문에서 예외가 발생하면 어떤일이 발생할까요?

2021-05-05 08:41 UTC, sigriswil commented on src/main/java/com/restaurant/eatenjoy/util/mail/HtmlMailService.java
> +			throw new NotFoundException("메일 양식을 찾을 수 없습니다.");
서버 구동이 중지됩니다.

2021-05-07 02:30 UTC, f-lab-dev commented on src/main/java/com/restaurant/eatenjoy/util/mail/HtmlMailService.java
> +			return "<!DOCTYPE html>\n<html>\n<head></head>\n<body>\n"
실서버라고 가정했을 때 파일을 읽는데에 실패한다면 이 기본값으로 몇일, 몇달동안 어플리케이션이 구동되는 상태일 수 있는데 괜찮은걸까요?

2021-05-07 03:57 UTC, sigriswil commented on src/main/java/com/restaurant/eatenjoy/util/mail/HtmlMailService.java
> +			return "<!DOCTYPE html>\n<html>\n<head></head>\n<body>\n"
서버 구동이 중지되지 않는 선에서 기본 양식으로 처리했는데 
서버 예외 띄우는게 더 나은 선택인가요??

2021-05-09 05:12 UTC, f-lab-dev commented on src/main/java/com/restaurant/eatenjoy/util/mail/HtmlMailService.java
> +			return "<!DOCTYPE html>\n<html>\n<head></head>\n<body>\n"
이거는 요구사항에 따라 다른 것 같습니다~ 기본 양식을 쭉 사용해도 상관이 없으면 둬도 괜찮겠지만, 아니라면 서버 실행을 못하게 해야할 것 같네요~

2021-05-10 06:51 UTC, f-lab-dev approved these changes

2021-05-10 06:52 UTC, f-lab-dev requested changes

2021-05-10 06:52 UTC, f-lab-dev commented on src/main/java/com/restaurant/eatenjoy/util/mail/HtmlMailService.java
> +	static {
static 구문으로 처리하기보다는 그냥 bean으로 두고 생성자에서 처리하면 어떨까요?

2021-05-11 10:38 UTC, f-lab-dev approved these changes

2021-05-11 10:54 UTC, merged